#spring.data.mongodb.uri=mongodb+srv://qodtn:1234@cluster0-1xs3x.gcp.mongodb.net/heartrate_db?retryWrites=true&w=majority
#spring.data.mongodb.database=heartrate_db

spring:
  data:
    mongodb:
      uri: mongodb+srv://qodtn:1234@cluster0-1xs3x.gcp.mongodb.net/heartrate_db?retryWrites=true&w=majority
      database: heartrate_db
  output:
    ansi:
      enabled: always

server:
  port: 8443 #SSL 사용할 포트 지정
  ssl:
#  /usr/games/cert.jks
        enabled: true
        key-store: /usr/games/cert.jks
        key-store-type: PKCS12
        key-store-password: 123456  # jks 또는 pfx 패스워드
        key-alias: trco.site # (필요시) Alias 명 지정. CSR 자동 생성시에는 CN 명

debug: false
logging:
  file: /usr/games/local
  level:
      root: info
